### ISSUE TITLE
Random Embed Bug

### ISSUE THREAD

**Issue by LIPDProductionsInc** [LIPDProductionsInc/Redwood_Automation#1]
### Error:

```Ignoring exception in command issue:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/home/pi/Documents/Redwood_Automation/cogs/redwood-automation-emergency.py", line 118, in issue
    await channel.send(embed=embed)
UnboundLocalError: local variable 'embed' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "/home/pi/.local/lib/python3.9/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'issue' raised an exception: UnboundLocalError: local variable 'embed' referenced before assignment
```

### Command Error Occurred On:
[EAS Issued Command](https://github.com/LIPDProductionsInc/Redwood_Automation/blob/main/cogs/redwood-automation-emergency.py#L28-L120)

### Role Error Occurred On:
Mayor

### Able to Re-Produce?
No

**Comment by LIPDProductionsInc** [comment]
@ThePugi Any idea? Lol

**Comment by ThePugi** [comment]
> @ThePugi Any idea? Lol

Likely that the "Level", for some reason, did not get caught by the if-elif block checks. I'd suspect that to be the root cause

**Comment by LIPDProductionsInc** [comment]
Alright. I can throw in a quick error catching

**Comment by LIPDProductionsInc** [comment]
Error catch triggered with "Major Weather Event" level. Fix was pushed earlier

**Comment by LIPDProductionsInc** [comment]
Above was fixed in https://github.com/LIPDProductionsInc/Redwood_Automation/commit/f59d8672518a7b928e0fc73dbc1ccc8dcbcda98f

**Comment by LIPDProductionsInc** [comment]
@ThePugi I think this bug is squashed now

**Comment by LIPDProductionsInc** [comment]
Wrong issue
