### ISSUE TITLE
TypeError for Adding a Link to the main Discord with the PD Embed

### ISSUE THREAD

**Issue by LIPDProductionsInc** [LIPDProductionsInc/Redwood_Automation#6]
```py
Ignoring exception in command issue:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/home/pi/Documents/Redwood_Automation/cogs/redwood-automation-emergency.py", line 136, in issue
    message += "\n\nFor more information, please visit the [Redwood City Discord](https://discord.gg/9XkQagqJGb)."
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "/home/pi/.local/lib/python3.9/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'issue' raised an exception: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by LIPDProductionsInc** [comment]
It's the EAS command again. Gonna look at the code to try and refresh my memory

**Comment by LIPDProductionsInc** [comment]
Fixed in latest build
